export const FETCH_WEEK_SENDED = 'FETCH_WEEK_SENDED';
export const RESPOND_WEEK_RCVD = 'RESPOND_WEEK_RCVD';

export const FETCH_DAY_SENDED = 'FETCH_DAY_SENDED';
export const RESPOND_DAY_RCVD = 'RESPOND_DAY_RCVD';
